export const CREATE_USER = 'CREATE_USER'
export const SET_USER_DATA = 'SET_USER_DATA'
export const READ_USER_FROM_DATABASE = 'READ_USER_FROM_DATABASE';
export const DELETE_DATABASE_USER = 'DELETE_DATABASE_USER';
export const UPDATE_DATABASE = 'UPDATE_DATABASE';
export const LOG_USER_IN = 'LOG_USER_IN';
