export const CREATE_SCAN = 'CREATE_SCAN';
export const GET_SCAN_HISTORY = 'GET_SCAN_HISTORY';
export const UPDATE_SCAN_DATABASE = 'UPDATE_SCAN_DATABASE';
export const DELETE_SCAN = 'DELETE_SCAN';
export const INCREMENT_VISITED = 'INCREMENT_VISITED';
